# This file contains the configuration for the dev environment.
# None of the values here are actually secret, so it's fine
# to commit this file to the repository.
server:
  ip: "127.0.0.1"
  port: 8000
templateconfig:
  dir: "../templates"
  pattern: "/**/*"
  extra_templates:
    - path: "index.html"
      name: "index"
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "rusty_flash_knowledge_db"
  require_ssl: false
authorization:
  api_key: "supersecretapikey"
